version: "3.8"

services:
  crypto-analyzer:
    build: .
    container_name: crypto-analyzer
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Tehran
